export const socketConstant = {
  SOCKET_REQUEST: 'SOCKET_REQUEST',
  LOGIN_SOCKET_CONNECTION: 'LOGIN_SOCKET_CONNECTION',
  DISCONNECT_SOCKET_CONNECTION: 'DISCONNECT_SOCKET_CONNECTION',
};
export const buildConstants = {
  BUILD_CONNECTION: 'BUILD_CONNECTION',
  BUILD_CONNECTION_SUCCESS: 'BUILD_CONNECTION_SUCCESS',
  BUILD_CONNECTION_FAIL: 'BUILD_CONNECTION_FAIL',

  GET_ALL_ACTIVE_CONNECTION_SUCCESS: 'GET_ALL_ACTIVE_CONNECTION_SUCCESS',
  GET_ALL_ACTIVE_CONNECTION_FAIL: 'GET_ALL_ACTIVE_CONNECTION_FAIL',

  NEW_CONNECTION_SUCCESS: 'NEW_CONNECTION_SUCCESS',
};

export const paymentMethodConstant = {
  QR_PAYMENT_REQUEST: 'QR_PAYMENT_REQUEST',
  QR_PAYMENT_SCAN_SUCCESS: 'QR_PAYMENT_SCAN_SUCCESS',
  QR_PAYMENT_SCAN_FAIL: 'QR_PAYMENT_SCAN_FAIL',

  QR_LOGIN_PASS_SUCCESS: 'QR_LOGIN_PASS_SUCCESS',
  QR_LOGIN_PASS_FAIL: 'QR_LOGIN_PASS_FAIL',

  QR_LOGIN_PASS_SEND_SMS_SUCCESS: 'QR_LOGIN_PASS_SEND_SMS_SUCCESS',
  QR_LOGIN_PASS_SEND_SMS_FAIL: 'QR_LOGIN_PASS_SEND_SMS_FAIL',
};

export const authConstant = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
export const salesConstant = {
  SALES_REQUEST: 'SALES_REQUEST',
  GET_SALES_SUCCESS: 'GET_SALES_SUCCESS',
  GET_SALES_FAIL: 'GET_SALES_FAIL',
};
